### ISSUE TITLE
Custom spawnmenu doesn't work if the UC category is first in the list

### ISSUE THREAD

**Issue by Fesiug** [Urban-Coalition/ArcCW_UC_Common#12]
Custom spawnmenu doesn't work if the ArcCW - Urban Coalition category is the first one in the list

**Comment by TheOnly8Z** [comment]
Investigating. Seems to be related to the first panel having it's population function called before our overwrite.

**Comment by TheOnly8Z** [comment]
Fixed in 128b3a12ceb437fa93bcfe8a8a401977267c7323.
