### ISSUE TITLE
Suppressors Lag

### ISSUE THREAD

**Issue by VaeAstra** [Urban-Coalition/ArcCW_UC_Common#8]
Shooting with suppressors on guns like the AR-15 and AKM make the game lag and turn it into a slideshow.

Also what happened to the GP-25 and HK69?

**Comment by Fesiug** [comment]
Sounds like a bug on your end.
The underbarrels are unfinished and we have a deadline to release Urban Renewal on the 25th, if you aren't in the know.

**Comment by Sninctbur** [comment]
Be sure that you've obtained an up-to-date copy of UC Common using Github Desktop, not the .zip download.

**Comment by ghost** [comment]
guy said this was fixed in the discord so you can probably close this
